version: '3.7'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      
  web:
    image: muggleskin/yamdb_final_web:latest
    restart: always
    expose:
      - 8000
    volumes:
      - ./static:/code/static
    depends_on:
      - db

  nginx:
    image: muggleskin/yamdb_final_nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./static:/code/static
    depends_on:
      - web